/*
 * nv.h
 *
 *  Created on: 12.12.2016.
 *      Author: milan
 */

#ifndef NV_H_
#define NV_H_

#include "stdint.h"

#define NV_OK         (0)   // value came out of the NV
#define NV_ERR        (1)   // access failed, or the stored value is corrupted
#define NV_ABSENT     (2)   // never written, or erased - a normal state, not a fault

typedef enum
{
	NV_ADDR_STATIC_START = 0,       // static variables are not deleted when reset to default
	NV_ADDR_STATIC_RESERVED0,

	NV_ADDR_STATIC_UNUSED0,         // was RETIRED_ILOAD_KTA, feature removed
	NV_ADDR_STATIC_UNUSED1,         // was RETIRED_ILOAD_KTB, feature removed
	NV_ADDR_STATIC_UNUSED2,         // was RETIRED_ILOAD_ZERO, feature removed

	NV_ADDR_START = 17,             // starting id of variables
	NV_ADDR_RESERVED0,

	NV_ADDR_BATT_PROFILE_ID,
	NV_ADDR_BATT_CAPACITY,
	NV_ADDR_CHARGE_CURRENT,
	NV_ADDR_CHARGE_TERM_CURRENT,
	NV_ADDR_BATT_REG_VOLTAGE,
	NV_ADDR_BATT_CUTOFF_VOLTAGE,
	NV_ADDR_BATT_TEMP_COLD,
	NV_ADDR_BATT_TEMP_COOL,
	NV_ADDR_BATT_TEMP_WARM,
	NV_ADDR_BATT_TEMP_HOT,
	NV_ADDR_BATT_NTC_B,
	NV_ADDR_BATT_NTC_RESISTANCE,
	NV_ADDR_BATT_NTC_XOR,

	NV_ADDR_FUEL_GAUGE_CONFIG_MASK,
	NV_ADDR_CHARGING_CONFIG,
	NV_ADDR_CHARGER_INPUTS_CONFIG,
	NV_ADDR_HOST_WDT_CONFIGL,

	NV_ADDR_RESERVED5,

	NV_ADDR_BUTTON_PRESS_FUNC_SW1,
	NV_ADDR_BUTTON_PRESS_CONFIG_SW1,
	NV_ADDR_BUTTON_RELEASE_FUNC_SW1,
	NV_ADDR_BUTTON_RELEASE_CONFIG_SW1,
	NV_ADDR_BUTTON_SINGLE_PRESS_FUNC_SW1,
	NV_ADDR_BUTTON_SINGLE_PRESS_CONFIG_SW1,
	NV_ADDR_BUTTON_DOUBLE_PRESS_FUNC_SW1,
	NV_ADDR_BUTTON_DOUBLE_PRESS_CONFIG_SW1,
	NV_ADDR_BUTTON_LONG_PRESS1_FUNC_SW1,
	NV_ADDR_BUTTON_LONG_PRESS1_CONFIG_SW1,
	NV_ADDR_BUTTON_LONG_PRESS2_FUNC_SW1,
	NV_ADDR_BUTTON_LONG_PRESS2_CONFIG_SW1,

	NV_ADDR_WAKEUPONCHARGE_CONFIG,

	NV_ADDR_BUTTON_PRESS_FUNC_SW2,
	NV_ADDR_BUTTON_PRESS_CONFIG_SW2,
	NV_ADDR_BUTTON_RELEASE_FUNC_SW2,
	NV_ADDR_BUTTON_RELEASE_CONFIG_SW2,
	NV_ADDR_BUTTON_SINGLE_PRESS_FUNC_SW2,
	NV_ADDR_BUTTON_SINGLE_PRESS_CONFIG_SW2,
	NV_ADDR_BUTTON_DOUBLE_PRESS_FUNC_SW2,
	NV_ADDR_BUTTON_DOUBLE_PRESS_CONFIG_SW2,
	NV_ADDR_BUTTON_LONG_PRESS1_FUNC_SW2,
	NV_ADDR_BUTTON_LONG_PRESS1_CONFIG_SW2,
	NV_ADDR_BUTTON_LONG_PRESS2_FUNC_SW2,
	NV_ADDR_BUTTON_LONG_PRESS2_CONFIG_SW2,

	NV_ADDR_RESERVED7,

	NV_ADDR_BUTTON_PRESS_FUNC_SW3,
	NV_ADDR_BUTTON_PRESS_CONFIG_SW3,
	NV_ADDR_BUTTON_RELEASE_FUNC_SW3,
	NV_ADDR_BUTTON_RELEASE_CONFIG_SW3,
	NV_ADDR_BUTTON_SINGLE_PRESS_FUNC_SW3,
	NV_ADDR_BUTTON_SINGLE_PRESS_CONFIG_SW3,
	NV_ADDR_BUTTON_DOUBLE_PRESS_FUNC_SW3,
	NV_ADDR_BUTTON_DOUBLE_PRESS_CONFIG_SW3,
	NV_ADDR_BUTTON_LONG_PRESS1_FUNC_SW3,
	NV_ADDR_BUTTON_LONG_PRESS1_CONFIG_SW3,
	NV_ADDR_BUTTON_LONG_PRESS2_FUNC_SW3,
	NV_ADDR_BUTTON_LONG_PRESS2_CONFIG_SW3,

	NV_ADDR_RESERVED8,

	NV_ADDR_LED_D1_FUNC,
	NV_ADDR_LED_D1_PARAM_R,
	NV_ADDR_LED_D1_PARAM_G,
	NV_ADDR_LED_D1_PARAM_B,
	NV_ADDR_UNUSED0,                // was LED_FUNC_2, feature removed
	NV_ADDR_UNUSED1,                // was LED_PARAM_R_2, feature removed
	NV_ADDR_UNUSED2,                // was LED_PARAM_G_2, feature removed
	NV_ADDR_UNUSED3,                // was LED_PARAM_B_2, feature removed

	NV_ADDR_RESERVED9,
	NV_ADDR_RESERVED10,

	NV_ADDR_POWER_REGULATOR_CONFIG,
	NV_ADDR_RUN_PIN_CONFIG,

	NV_ADDR_RESERVED11,

	NV_ADDR_OWN_ADDRESS1,
	NV_ADDR_OWN_ADDRESS2,
	NV_ADDR_ID_EEPROM_ADR,

	NV_ADDR_RESERVED12,

	NV_ADDR_IO_CONFIG1,
	NV_ADDR_IO_CONFIG1_PARAM1,
	NV_ADDR_IO_CONFIG1_PARAM2,
	NV_ADDR_IO_CONFIG2,
	NV_ADDR_IO_CONFIG2_PARAM1,
	NV_ADDR_IO_CONFIG2_PARAM2,

	NV_ADDR_RESERVED13,

	NV_ADDR_BAT_CHEMISTRY,
	NV_ADDR_BAT_OCV10L,
	NV_ADDR_BAT_OCV10H,
	NV_ADDR_BAT_OCV50L,
	NV_ADDR_BAT_OCV50H,
	NV_ADDR_BAT_OCV90L,
	NV_ADDR_BAT_OCV90H,
	NV_ADDR_BAT_R10L,
	NV_ADDR_BAT_R10H,
	NV_ADDR_BAT_R50L,
	NV_ADDR_BAT_R50H,
	NV_ADDR_BAT_R90L,
	NV_ADDR_BAT_R90H,
	NV_ADDR_HOST_WDT_CONFIGH,
	NV_ADDR_NUM
} NvAddr_T;

uint8_t nv_Init(void);

uint8_t nv_Erase(void);

uint8_t nv_write_U8(uint16_t _addr, uint8_t _var);

/*
 * Reads return NV_OK, NV_ABSENT or NV_ERR, and touch *_p_var only on NV_OK - so the caller can
 * preload it with its default and ignore the result. Only NV_ERR is logged as an error.
 */
uint8_t nv_read_U8(uint16_t _addr, uint8_t *_p_var);

uint8_t nv_write_U16(uint16_t _addr, uint16_t _var);

uint8_t nv_read_U16(uint16_t _addr, uint16_t *_p_var);

#endif /* NV_H_ */
